### ISSUE TITLE
Admin page redesign/reconstruction to meet the standards

### ISSUE THREAD

**Issue by albannurkollari** [IvanCybercom/Hackademy-IV-frontend#131]
### Even though there is no request to style **Admin** side of the project less or the same as **Donor** side, it still needs to have a better visual feeling in the opposite that it now has. E.g. _links_ on the top side of the page act like _button_, whereas they could fit into a nested menu as real links etc.

**Comment by alayham** [comment]
@albannurkollari what is the status of this issue?

**Comment by albannurkollari** [comment]
@alayham Depends on your definition of the DONE. You can pull the branch and see it. I and many others remember exactly what Ivan told us about that Admin is not gonna be used on mobile devices, just desktop version is requested in MVP. I have finished styling Sidebar and some other related stuff to be mobile friendly responsive. BUT, then the rest of the pages we have designed are broken in mobility.

**Comment by alayham** [comment]
well, you have my approval to merge. why don't you create a pull request for it. 
Mobile support can be added later by somebody else if requested by the P.O.
