### ISSUE TITLE
changing the project json file.

### ISSUE THREAD

**Issue by sheon** [IvanCybercom/Hackademy-IV-frontend#134]
I am changing the project.json file to include the events for each project. Thus, to better organize the images of the projects, each project has its own folder named as project001, including two subfolders named as main (main picture of the project) and events (one picture per event numbered from 1 increasing as the new events are added to the project).

**Comment by alayham** [comment]
I suggest creating a new "blog" or "events" entity that contains entries, each entry has a project id, and a new component to show entries, then you use the component to show the blog entries of a project in the project page.
This is how blogs will be represented in the DB, and this is a lot easier and more flexible, and does not require any update on the existing code.

@IvanCybercom what do you think?

**Comment by ticooo95** [comment]
and you also added a new property for the projects interface , openProject : boolean

**Comment by alayham** [comment]
If you put blog entries inside the project entity, and if admin wants to see the latest updates of all projects, then admin must load all project to be able to see their latest updates.

If you create a new entity for blog entries, then you can access all entries if needed without loading any all projects, or the entries of a specific project as you expect the use case to be.

**Comment by sheon** [comment]
I understand what Al says. Please spare sometime to think about what Al suggests and let me know what you think. I can change the file.

**Comment by Mhd-Yaseen** [comment]
I agree with Al, it's better for the DB also, because some projects won't have any post, and some of them will have many posts.

and because we are dealing with RDBMS and not non-relational databases, for me that makes more sense.

**Comment by sheon** [comment]
The event is now a separate JSON and interface. 
new pull request been created #138

**Comment by alayham** [comment]
fixed in #138
