### ISSUE TITLE
local storage

### ISSUE THREAD

**Issue by Mhd-Yaseen** [IvanCybercom/Hackademy-IV-frontend#136]
Storing the user saved projects and funded project in the local storage.

- [ ] read about local storage.

**Comment by alayham** [comment]
I think we need to introduce the product owner to the risks of using local storage. We could show him how the local storage can be manipulated from the browser console, and let him decide if he wants to take the risks of storing information there.

If the product owner accepts the risks, I guess anything stored in the local storage should have a copy on the backend. Besides, we need to ask the product owner about handling "dead accounts" which are stored on the server and do not have any recent sessions, and there is no way to communicate with their owner.

**Comment by alayham** [comment]
We could propose to the product owner to use local storage in the mobile app only, not in the web app. 

In the mobile app, we can have other ways to identify the user, and to enable him to contact the user when needed.

**Comment by Mhd-Yaseen** [comment]
@alayham We had a long discussion with the product owner today and we have changed many things about the wallet and storing data for unregistered users.
I will tell you everything on Friday.

**Comment by alayham** [comment]
fixed in #182
