### ISSUE TITLE
Admin - Data Service Update for both Organizations/Projects

### ISSUE THREAD

**Issue by albannurkollari** [IvanCybercom/Hackademy-IV-frontend#50]
# **data.service.ts** file must be reworked and the previous code should stay as it is but labeled as depricated in order to not break code which is currently functioning. 

- New specific naming of functions should be implemented and the approach should reflect directa access of the functions instead of grouping them as properties under a object type variable.
- Setting input data that admin/user provides in form(s) connected with the service should be provided in data.service.ts file. Either _PUT/POST_ methods should be used to achieve the intented result(s).
- In the end, after the result(s) and the previous nodes are checked a thorough advanced testing should be written and run in order to provide a clean and no error-prone coding.
- (Optional) Additional documenting, such as commenting snippets/blocks of code is welcomed to explain what/why/how does that part of the code provide.

**Comment by alayham** [comment]
This has failed, and should be closed.
