### ISSUE TITLE
[Admin] [Org Form] The length of organization number is hardcoded

### ISSUE THREAD

**Issue by alayham** [IvanCybercom/Hackademy-IV-frontend#70]
`      <md-hint align="end">{{orgNumber.value.length}} / 6</md-hint>`

organization-form.component.html

consider declaring this as a constant in the component or somewhere else, and binding to it.

**Comment by alayham** [comment]
RTBM

**Comment by ticooo95** [comment]
i've done this with OrgNumber validator , so i think this is ready to close

**Comment by ticooo95** [comment]
did it on #98 pull req
